import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Manrope} from "next/font/google";
import { Footer, Header } from "./components";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const manrope = Manrope({
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--manrope",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${manrope.variable}`}>
        <Header/>
         <main className="flex-1">
          {children}
        </main>
        <Footer/>
        </body>
    </html>
  );
}
